
# GITHUB ISSUES REPORT FOR microsoft/vscode-python


Generated on 2023-04-01 using: stale=30, all=0


Only showing items that are new to report in past 1 day(s)


## FOR ISSUES THAT ARE MARKED AS BUGS:


### Issues in vscode-python that have comments from 3rd party after last team response:


\* [10722](https://github.com/microsoft/vscode-python/issues/10722 "Debugging test in VS Code does not work"): 3rd party responded 0 days ago but team last responded 280 days ago

---

## FOR ISSUES THAT ARE NOT MARKED AS BUGS:


### Issues in vscode-python that need a response from team:


\* [20959](https://github.com/microsoft/vscode-python/issues/20959 "Automatically create requirements.txt"): needs an initial team response (0 days old)

\* [20964](https://github.com/microsoft/vscode-python/issues/20964 "Python Packages/Libraries Not Recognized"): needs an initial team response (1 days old)

### Issues in vscode-python that have comments from OP after last team response:


\* [20859](https://github.com/microsoft/vscode-python/issues/20859 "Create a Python for Education profile "): OP responded 1 days ago but team last responded 16 days ago

\* [20962](https://github.com/microsoft/vscode-python/issues/20962 "Cannot debug Python tests, got message Invalid message: Found duplicate in &quot;env&quot;: PATH"): OP responded 0 days ago but team last responded 0 days ago

\* [20963](https://github.com/microsoft/vscode-python/issues/20963 "Syntax Highlighting Error"): OP responded 0 days ago but team last responded 0 days ago

### Issues in vscode-python that have comments from 3rd party after last team response:


\* [14695](https://github.com/microsoft/vscode-python/issues/14695 "Go to next line"): 3rd party responded 1 days ago but team last responded 869 days ago

\* [20828](https://github.com/microsoft/vscode-python/issues/20828 "Invalid message: Found duplicate in &quot;env&quot;: PATH when using virtual environment in Python 3.11"): 3rd party responded 0 days ago but team last responded 1 days ago

\* [20843](https://github.com/microsoft/vscode-python/issues/20843 "ERROR conda.cli.main_run:execute(49)"): 3rd party responded 0 days ago but team last responded 16 days ago
